export {default as Login} from './Login';
export {default as SignUp} from './SignUp';
export {default as Home} from './Home';
export {default as Presentation} from './Presentation';
export {default as ClassroomStrategies} from './ClassroomStrategies';
export {default as SignificantMethodologies} from './SignificantMethodologies';
export {default as KnowledgeLibrary} from './KnowledgeLibrary';
export {default as Profile} from './Profile';
export {default as LanguageSpace} from './LanguageSpace';
